apiVersion: v2
name: cloudlab-hf
description: I53LZ8
type: application
version: 1.0.0
appVersion: "1.0.0"

# Köszi bitnami
#dependencies:
#  - name: redis
#    version: "19.6.1"
#    repository: https://charts.bitnami.com/bitnami
#    alias: my-redis
#  - name: minio
#    version: "12.8.3"
#    repository: https://charts.bitnami.com/bitnami
#    alias: my-minio