apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud_hf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud_hf
  template:
    metadata:
      labels:
        app: cloud_hf
    spec:
      containers:
      - name: frontend
        image: sloweroons/cloud_hf:latest
        imagePullPolicy:
        ports:
        - containerPort: 3000