apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-hf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-hf
  template:
    metadata:
      labels:
        app: cloud-hf
    spec:
      containers:
      - name: frontend
        image: sloweroons/cloud-hf:latest
        imagePullPolicy:
        ports:
        - containerPort: 3000