--- # App deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-hf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-hf
  template:
    metadata:
      labels:
        app: cloud-hf
    spec:
      containers:
      - name: frontend
        image: sloweroons/cloud-hf:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000  
--- # Flask service
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: cloud-hf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
--- # Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocr-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-service
            port:
              number: 80