--- # Flask deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-hf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-hf
  template:
    metadata:
      labels:
        app: cloud-hf
      annotations:
        rollout-trigger: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: frontend
        image: sloweroons/cloud-hf:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Europe/Budapest"
        ports:
        - containerPort: 5000  
--- # Flask service
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: cloud-hf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
--- # Ingress Controller External -> Flask
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocr-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-service
            port:
              number: 80
--- # Ingress Controller Minikube -> MinIO
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /minio/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: manual-minio-service
            port:
              number: 9000
--- # Redis deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manual-redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: manual-redis
  template:
    metadata:
      labels:
        app: manual-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        args: ["redis-server", "--requirepass", "adminpass"]
        ports:
        - containerPort: 6379
--- # Redis service
apiVersion: v1
kind: Service
metadata:
  name: manual-redis-service
spec:
  selector:
    app: manual-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
--- # MinIO deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manual-minio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: manual-minio
  template:
    metadata:
      labels:
        app: manual-minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        imagePullPolicy: IfNotPresent
        args: ["server", "/data", "--console-address", ":9090"]
        env:
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "adminpass"
        ports:
        - containerPort: 9000
        - containerPort: 9090
--- # MinIO service
apiVersion: v1
kind: Service
metadata:
  name: manual-minio-service
spec:
  selector:
    app: manual-minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
# Worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator-worker
  template:
    metadata:
      labels:
        app: operator-worker
    spec:
      containers:
      - name: worker
        image: sloweroons/cloud-worker:latest
        imagePullPolicy: Always